FROM wordpress:latest

# Example: Add custom plugins or themes here
# COPY plugins /var/www/html/wp-content/plugins
# COPY themes /var/www/html/wp-content/themes

# Add custom plugin
COPY custom-content /var/www/html/wp-content/plugins/custom-content

EXPOSE 80
