apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-cron
  namespace: default
spec:
  schedule: "*/5 * * * *"          # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:8.10.1
              command: ["sh", "-c"]
              args:
                - "ts=$(date +%s); curl -fsS --max-time 20 \"https://devsecops2025-arubacloud.com/wp-cron.php?doing_wp_cron=$ts\""
