apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: apache-conf
          configMap:
            name: wordpress-apache-conf
        - name: mu-plugins
          configMap:
            name: wordpress-mu-plugins
      initContainers:
        - name: enable-servername
          image: bash:5.2
          command: ["bash","-lc","a2enconf servername || true"]
          volumeMounts:
            - name: apache-conf
              mountPath: /etc/apache2/conf-available/servername.conf
              subPath: servername.conf
      containers:
        - name: wordpress
          image: wordpress:6.6.2-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                // Trust ingress proxy scheme
                if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
                    $_SERVER['HTTPS'] = 'on';
                    $_SERVER['SERVER_PORT'] = 443;
                }

                // Pin canonical host to avoid weird ports in URLs
                $_SERVER['HTTP_HOST'] = 'devsecops2025-arubacloud.com';

                // Canonical HTTPS URLs
                if (!defined('WP_HOME')) define('WP_HOME', 'https://devsecops2025-arubacloud.com');
                if (!defined('WP_SITEURL')) define('WP_SITEURL', 'https://devsecops2025-arubacloud.com');

                // Force SSL for admin
                if (!defined('FORCE_SSL_ADMIN')) define('FORCE_SSL_ADMIN', true);

                // Disable built-in cron (K8s CronJob handles it)
                if (!defined('DISABLE_WP_CRON')) define('DISABLE_WP_CRON', true);

          volumeMounts:
            - name: apache-conf
              mountPath: /etc/apache2/conf-enabled/servername.conf
              subPath: servername.conf
            - name: mu-plugins
              mountPath: /var/www/html/wp-content/mu-plugins

          readinessProbe:
            httpGet: { path: /wp-includes/images/blank.gif, port: 80 }
          livenessProbe:
            httpGet: { path: /wp-includes/images/blank.gif, port: 80 }

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
