apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-apache-conf
  namespace: default
data:
  servername.conf: |
    ServerName devsecops2025-arubacloud.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mu-plugins
data:
  00-canonical-urls.php: |
    <?php
    // Make WordPress see HTTPS when behind ingress
    if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && stripos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
      $_SERVER['HTTPS'] = 'on';
    }
    // Force canonical public URLs (before DB options are read)
    add_filter('pre_option_home',    fn($v) => 'https://devsecops2025-arubacloud.com');
    add_filter('pre_option_siteurl', fn($v) => 'https://devsecops2025-arubacloud.com');
    if (!defined('FORCE_SSL_ADMIN')) {
      define('FORCE_SSL_ADMIN', true);
    }
