apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: apache-conf
          configMap:
            name: wordpress-apache-conf
        - name: mu-plugins
          configMap:
            name: wordpress-mu-plugins
            items:
              - key: 00-canonical-urls.php
                path: 00-canonical-urls.php
      initContainers:
        - name: enable-servername
          image: bash:5.2
          command: ["bash","-lc","a2enconf servername || true"]
          volumeMounts:
            - name: apache-conf
              mountPath: /etc/apache2/conf-available/servername.conf
              subPath: servername.conf
      containers:
        - name: wordpress
          image: wordpress:6.6.2-apache
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_PASSWORD
          volumeMounts:
            - name: apache-conf
              mountPath: /etc/apache2/conf-enabled/servername.conf
              subPath: servername.conf
            - name: mu-plugins
              mountPath: /var/www/html/wp-content/mu-plugins
              readOnly: true

          readinessProbe:
            httpGet: { path: /wp-includes/images/blank.gif, port: 80 }
          livenessProbe:
            httpGet: { path: /wp-includes/images/blank.gif, port: 80 }

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
