apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"   # shorter DNS is safer
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"             # must match your Vault auth mount
          role: "eso-app"                     # must exist in Vault
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets